[package]
name = "ggml"
version = "0.1.0-rc1"
repository = { workspace = true }
edition = "2021"
description = "Semi-idiomatic Rust bindings for the ggml library (from `ggml-sys`)."
license = "MIT"

[dependencies]
thiserror = { workspace = true }
ggml-sys = { path = "sys", version = "0.1.0-rc1" }

[dev-dependencies]
rand = { workspace = true }
